# Runtime helpers for er-adam-spec-reader.
# Mirrors signatures in code_corpus/adam_spec_ingestion_library.R; the corpus
# is reference documentation (not sourced at runtime), this file is the
# implementation. Inline chunks generated by Core 1's 01_understanding_data_inventory
# call these functions. All readers return NULL when the spec is absent or
# unreadable, so Core 1 falls through to filename-pattern role inference for
# studies without an ADaM specification workbook.

`%||%` <- function(x, y) if (is.null(x) || length(x) == 0 || all(is.na(x))) y else x

# ---- Role classification --------------------------------------------------
